# version: '3.5'
services:
  pg_hibernate_exercise_1_5:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - ./pg_volume_chatgpt4o_hibernate_exercise_1_5:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    container_name: pg_hibernate_exercise_1_5
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  pg_hibernate_exercise_3:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - ./pg_volume_chatgpt4o_hibernate_exercise_3:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5433:5432"
    container_name: pg_hibernate_exercise_3
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  pg_hibernate_myself_1_trips:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - ./pg_volume_hibernate_myself_1_trips\:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5434:5432"
    container_name: pg_hibernate_myself_1_trips
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  pg_hibernate_one_many_many:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - ./pg_volume_one_many_many:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5435:5432"
    container_name: pg_hibernate_one_many_many
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  pg_hibernate_one_many_many_docs_item_group:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    volumes:
      - ./pg_volume_one_many_many_docs_item_group:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5436:5432"
    container_name: pg_hibernate_one_many_many_docs_item_group
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  pg_formatter:
    build: pg_formatter
    container_name: pg_formatter_service
    depends_on:
      - pg_hibernate_one_many_many
      - pg_hibernate_one_many_many_docs_item_group